### ISSUE TITLE
⭐️ Validate File

### ISSUE THREAD

**Issue by marlon360** [marlon360/nifty-uploader#23]
**Describe the solution you'd like**
Run validation functions in the processing step.
Custom validation function in options.
By default validate the file type.
Specify filetypes in options.

**Comment by ahungrynoob** [comment]
These are several points I think should be considered;

- processing files (check file types and size) before add them (do this in `class NiftyUploader`) ;
- create errorCall hook in option enabling users to control the upload process.
- I think it'd better put file processing function in NiftyUploader Class

**Comment by marlon360** [comment]
- added validation for size and type
- added events for processing error and success
